# Generated by Django 5.1.1 on 2024-10-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_livro_categoria_livro_editora"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="autor",
            field=models.ManyToManyField(blank=True, related_name="livros", to="core.autor"),
        ),
    ]
