# Generated by Django 5.1.4 on 2025-01-09 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_compra_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compra",
            name="data",
        ),
    ]
