# Generated by Django 5.1.4 on 2025-01-16 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_compra_tipo_pagamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itenscompra",
            name="livro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="itens_compra", to="core.livro"
            ),
        ),
    ]
